# File: .github/workflows/run_analysis.yml

name: Run Stock Analysis

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    # ---- ADD THIS PERMISSIONS BLOCK ----
    permissions:
      contents: write
    # ------------------------------------

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --pre pandas-ta==0.4.67b0 pandas==2.3.2 yfinance==0.2.65 numpy==1.23.5

      - name: Run stock analysis script
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: python scheduled_analysis.py
      
      - name: Commit analysis history
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📈 Update analysis history"
          file_pattern: analysis_history.csv
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com
